-- DB 프롬프트 간소화: 재료 이름을 영어로 변환하여 저장
UPDATE ingredients SET image_prompt = 'tomato' WHERE name = '토마토';
UPDATE ingredients SET image_prompt = 'potato' WHERE name = '감자';
UPDATE ingredients SET image_prompt = 'mushroom' WHERE name = '버섯';
UPDATE ingredients SET image_prompt = 'onion' WHERE name = '양파';
UPDATE ingredients SET image_prompt = 'pumpkin' WHERE name = '호박';
UPDATE ingredients SET image_prompt = 'carrot' WHERE name = '당근';
UPDATE ingredients SET image_prompt = 'cabbage' WHERE name = '양배추';
UPDATE ingredients SET image_prompt = 'broccoli' WHERE name = '브로콜리';
UPDATE ingredients SET image_prompt = 'spinach' WHERE name = '시금치';
UPDATE ingredients SET image_prompt = 'lettuce' WHERE name = '상추';
UPDATE ingredients SET image_prompt = 'cucumber' WHERE name = '오이';
UPDATE ingredients SET image_prompt = 'eggplant' WHERE name = '가지';
UPDATE ingredients SET image_prompt = 'bell pepper' WHERE name = '파프리카';
UPDATE ingredients SET image_prompt = 'zucchini' WHERE name = '애호박';
UPDATE ingredients SET image_prompt = 'radish' WHERE name = '무';
UPDATE ingredients SET image_prompt = 'garlic' WHERE name = '마늘';
UPDATE ingredients SET image_prompt = 'ginger' WHERE name = '생강';
UPDATE ingredients SET image_prompt = 'green onion' WHERE name = '파';
UPDATE ingredients SET image_prompt = 'chili pepper' WHERE name = '고추';
UPDATE ingredients SET image_prompt = 'corn' WHERE name = '옥수수';
UPDATE ingredients SET image_prompt = 'pork' WHERE name = '돼지고기';
UPDATE ingredients SET image_prompt = 'beef' WHERE name = '소고기';
UPDATE ingredients SET image_prompt = 'chicken' WHERE name = '닭고기';
UPDATE ingredients SET image_prompt = 'duck' WHERE name = '오리';
UPDATE ingredients SET image_prompt = 'lamb' WHERE name = '양고기';
UPDATE ingredients SET image_prompt = 'shrimp' WHERE name = '새우';
UPDATE ingredients SET image_prompt = 'crab' WHERE name = '게';
UPDATE ingredients SET image_prompt = 'squid' WHERE name = '오징어';
UPDATE ingredients SET image_prompt = 'octopus' WHERE name = '문어';
UPDATE ingredients SET image_prompt = 'clam' WHERE name = '조개';
UPDATE ingredients SET image_prompt = 'salmon' WHERE name = '연어';
UPDATE ingredients SET image_prompt = 'tuna' WHERE name = '참치';
UPDATE ingredients SET image_prompt = 'water' WHERE name = '물';
UPDATE ingredients SET image_prompt = 'apple' WHERE name = '사과';
UPDATE ingredients SET image_prompt = 'banana' WHERE name = '바나나';
UPDATE ingredients SET image_prompt = 'strawberry' WHERE name = '딸기';
UPDATE ingredients SET image_prompt = 'lemon' WHERE name = '레몬';
UPDATE ingredients SET image_prompt = 'orange' WHERE name = '오렌지';
UPDATE ingredients SET image_prompt = 'grape' WHERE name = '포도';
UPDATE ingredients SET image_prompt = 'watermelon' WHERE name = '수박';
